# -*- coding: utf-8 -*-
"""prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wd1l_oF7zVsMOm3-pbFbqAIyLcWUYNPo
"""

# Pedir al usuario que ingrese su nombre
nombre = input("Por favor, ingresa tu nombre: ")

# Imprimir un saludo personalizado
print("¡Hola,", nombre + "! Bienvenido al mundo de Python.")